blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/eremos-org/eremos/tree/main/docs
    about: Check the documentation for guides and API references
  - name: 💬 Discussions
    url: https://github.com/eremos-org/eremos/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: mailto:security@eremos.org
    about: Report security vulnerabilities privately via email